spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema="bankingplus"
        username: postgres
        password: rootpw
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    session:
        store-type: jdbc
        timeout: 6000
        jdbc:
            initialize-schema: always
            
server:
    port: 8090