spring:
    datasource:
        driverClassName: org.postgresql.Driver
        # url: jdbc:postgresql://localhost:5432/postgres?currentSchema="bankingplus"
        # username: postgres
        # password: rootpw
        url: jdbc:postgresql://kboadb.cjtgqrath0m4.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema="bankingplus"
        username: postgres
        password: rootpassword
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    session:
        store-type: jdbc
        timeout: 6000
        jdbc:
            initialize-schema: always
            
server:
    port: 8084
    servlet:
        session:
            cookie:
                same-site: none